# Docker image that runs our ci jobs
image: node:16-alpine

# Stages to be executed
stages:
  - setup
  - test

# Installs node_modules if package-lock.json has changed
install-dependencies:
  stage: setup
  interruptible: true
  only:
    changes:
      - package-lock.json
  cache:
    # We want to scope our cache to the current mr
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules

# Pulls the cached folders and updates cache after running
# The nx cache lives under node_modules. So we want to update it after execution.
cache: &global_cache
  key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
  paths:
    - node_modules/
  policy: pull-push

# Runs unit tests
test:
  stage: test
  interruptible: true
  cache:
    <<: *global_cache
  script:
    # We need to add git until we have a custom docker build image
    - apk update && apk add git
    - npx nx affected --base=HEAD~1 --target=test --parallel=2
