name: "Prepare to run nx affected jobs"
description: "Runs npm ci or loads from cache"
#inputs:
#  is_pull_request:
#    description: 'Prepares for running in a pull request'
#    required: true
#    default: false

runs:
  using: "composite"
  steps:

    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0

    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v2

    - name: Prepare node_modules
      uses: ./.github/actions/npm_ci
