name: "Upload build artifacts"
description: "Uploads build artifacts as zip file"

runs:
  using: "composite"
  steps:
    - name: Find affected
      id: find-affected
      shell: bash
      # Returns: hasAffected, hasAffectedE2e, hasAffectedApps, apps
      run: echo "::set-output name=affected::$(node ./tools/find-affected.js)"

    - name: Zip build artifact
      if: ${{ fromJSON(steps.find-affected.outputs.affected).hasAffectedApps }}
      shell: bash
      run: zip -r build.zip . -i ./dist/* -x ./dist/cypress/\*

    - name: Archive build artifact
      if: ${{ fromJSON(steps.find-affected.outputs.affected).hasAffectedApps }}
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: dist
