# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pull Request

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
#  dependencies:
  #
  #    runs-on: ubuntu-latest
  #
  #    steps:
  #      - uses: actions/checkout@v2
  #      - uses: ./.github/actions/npm_ci

  affected:

    runs-on: ubuntu-latest

    steps:
      # For branches
      - name: "Checkout repository for running on branches"
        uses: actions/checkout@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          fetch-depth: 0

      # For pull requests
      - name: "Checkout repository for running on pull request"
        uses: actions/checkout@v2
        if: ${{ github.event_name == 'pull_request' }}
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2

      - name: Prepare node_modules
        uses: ./.github/actions/npm_ci

      - name: Lint affected
        run: npx nx run-many --target=lint --all --parallel

      - name: Test affected
        run: npx nx run-many --target=test --all --parallel

      - name: Build affected
        run: npx nx run-many --target=build --all --parallel
