# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pull Request

on:
  #  push:
  #    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  dependencies:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/npm_ci

  lint:

    runs-on: ubuntu-latest
    needs: [ dependencies ]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: ./.github/actions/npm_ci
      - run: npx nx affected --target=lint --parallel

  test:

    runs-on: ubuntu-latest
    needs: [ dependencies ]

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/npm_ci
      - run: npx nx run-many --target test -c hamburger --all --parallel
